# Generated by Django 4.2 on 2024-02-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_options_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number_pic',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер картинки'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
    ]
