# Generated by Django 4.2 on 2024-02-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number_pic',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Номер картинки'),
        ),
    ]
